name = "alger-music-worker-v2"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
SECRET_DOMAIN = "*"
DEFAULT_SERVER = "netease"
DEFAULT_BR = "320"
CACHE_MAX_AGE = "300"
PICSIZE = "300"
LRCTYPE = "0"
AUTH_ENABLED = "false"
DEBUG_ALLOW_ALL_REFERERS = "true"